platform:ios,'8.0'
target "iOSTool" do
pod 'AFNetworking'
pod 'PPNetworkHelper',:git => 'https://github.com/jkpang/PPNetworkHelper.git'
pod 'SDWebImage'
pod 'MJRefresh'
pod 'SVProgressHUD'
pod 'TPKeyboardAvoiding'
pod 'MJExtension'
#pod 'HMSegmentedControl'
pod 'YYCache'
pod 'YYText'
pod 'MBProgressHUD'
pod 'STPickerView'
pod 'SDCycleScrollView'
pod 'ZYCornerRadius', '~> 1.0.2'
pod 'UITableView+FDTemplateLayoutCell'
pod 'Masonry'
pod 'RSKImageCropper'
pod 'TZImagePickerController'


#pod 'TXLiteAVSDK_Smart', :podspec => 'http://pod-1252463788.cosgz.myqcloud.com/liteavsdkspec/TXLiteAVSDK_Smart.podspec'

pod 'FMDB'
pod 'PleaseBaoMe'
pod "Qiniu"
pod 'ZFPlayer'
pod 'ZFDownload'



pod 'RongCloudIM/IMLib'
pod 'RongCloudIM/IMKit'
#pod 'UMengAnalytics'
pod 'UMCAnalytics'
pod 'UMCCommon'
pod 'UMCSecurityPlugins'
pod 'JPush'
#pod 'JAnalytics'
#pod 'UMCPush'
#pod 'UMengUShare/UI’, '<= 6.4.8'
#pod 'UMengUShare/Social/WeChat', '<= 6.4.8'
#pod 'UMengUShare/Social/ReducedQQ', '<= 6.4.8'
#pod 'UMengUShare/Social/Sina'

#pod 'JPush'

end
